### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by MarioRuiz** [d-theus/vncrec-ruby#1]
I'm trying to get screenshots instead of video
Is it possible some way?

**Comment by d-theus** [comment]
It is possible.
`vncrec -r 3 -o out%d.jpg`
I.e. use `-r` (for framerate) and filename format as if you were [making thumbnails with bare ffmpeg](https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video).
