### ISSUE TITLE
password to access the vnc

### ISSUE THREAD

**Issue by MarioRuiz** [d-theus/vncrec-ruby#3]
It seems like I cannot connect the vnc server since it is necessary to supply a password and it is not implemented in the code
r = VNCRec::Recorder.new(filename: "myvncsession.mp4", host: '192.168.43.55', port: 0, password: 'ssss')
r.run

**Comment by d-theus** [comment]
a1f71f94669b3bd8577df53de6a7bab2b9e46e2c
