### ISSUE TITLE
Empty file while recording videos with compression (using ffmpeg)

### ISSUE THREAD

**Issue by kevinmuller** [d-theus/vncrec-ruby#5]
Hi.

First of all, thanks for this great tool. It works perfectly fine with raw videos.

When I attempt to create a compressed video (after installation of ffmpeg), I get an empty file. The same issue happens for both MP4 and SWF format.

This is the command I am using:
`vncrec -s 192.168.0.105 -r 24  -g 1900x1880  -o ./video.flv`

I have tried a lot of different variations too.

And this is the output I am getting:
`ffmpeg version 3.2.4-1~bpo8+1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --extra-version='1~bpo8+1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --disable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, rawvideo, from 'pipe:0':
  Duration: N/A, bitrate: 2743296 kb/s
    Stream #0:0: Video: rawvideo (BGRA / 0x41524742), bgra, 1900x1880, 2743296 kb/s, 24 tbr, 24 tbn, 24 tbc
Output #0, flv, to './video.flv':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: flv1 (flv) ([2][0][0][0] / 0x0002), yuv420p, 1900x1880, q=2-31, 200 kb/s, 24 fps, 1k tbn, 24 tbc
    Metadata:
      encoder         : Lavc57.64.101 flv
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> flv1 (flv))
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)`

At the end I get a file that is a few bits only, and that can't be read.

Do you have any idea what could be the issue? 

Some more information:
OS: Debian Jessie
FFMPEG: version 3.2.4-1~bpo8+1

Thanks in advance.

Kevin

**Comment by d-theus** [comment]
Hello, @kevinmuller.
I understand that you've most probably abandoned an idea to use this gem after a while, but...

Can't reproduce your problem with various filenames, using ffmpeg 3.3. (vncrec was initially tested on even earlier versions than 3.2, so, I suppose, this isn't a 3.2-specific problem). Did you try to use the `--logging` option to receive some additional info?

**Comment by iamacarpet** [comment]
Hello @d-theus ,

I'm getting the same thing on Debian Jessie.

Just end up with an empty file and in htop, where I'd expect ffmpeg to be running, I just see a "sh" running in zombie state.

**Comment by d-theus** [comment]
Ok, I've fixed this in https://github.com/d-theus/vncrec-ruby/releases/tag/v1.0.6
