### ISSUE TITLE
Incomplete videos

### ISSUE THREAD

**Issue by somejavadev** [d-theus/vncrec-ruby#6]
Hi,  
   
Not sure if there is still support for this library but when recording without another VNC client connected to the VNC server (eg. Only vncrec is connected to the vnc server no other clients) I am getting really small videos or incomplete videos when recording for a couple of seconds and then stopping. When comparing it to when I have another vnc client connected with the --logging option specified there only seems to be a single (Got response: type 0) entry where there are multiple ones when I have another vnc client connected:
Failed video:
```
I, [% d_06  11-14-22.993456#3552]  INFO -- : connecting to localhost:5977
I, [% d_06  11-14-22.993760#3552]  INFO -- : connection established
I, [% d_06  11-14-23.248648#3552]  INFO -- : server geometry: 1360x1020
I, [% d_06  11-14-23.248706#3552]  INFO -- : requested geometry: 1360x1020
I, [% d_06  11-14-23.250497#3552]  INFO -- : Ok. Server: 09bb6e5756aa:99.0
I, [% d_06  11-14-24.066903#3552]  INFO -- : Got response: type 0
```
Working video:
```
I, [% d_06  11-10-59.449253#2831]  INFO -- : connecting to localhost:5977
I, [% d_06  11-10-59.449516#2831]  INFO -- : connection established
I, [% d_06  11-10-59.588344#2831]  INFO -- : server geometry: 1360x1020
I, [% d_06  11-10-59.588454#2831]  INFO -- : requested geometry: 1360x1020
I, [% d_06  11-10-59.590519#2831]  INFO -- : Ok. Server: 09bb6e5756aa:99.0
I, [% d_06  11-10-59.678629#2831]  INFO -- : Got response: type 0
I, [% d_06  11-10-59.745254#2831]  INFO -- : Got response: type 0
I, [% d_06  11-10-59.817869#2831]  INFO -- : Got response: type 0
I, [% d_06  11-10-59.889581#2831]  INFO -- : Got response: type 0
I, [% d_06  11-10-59.959474#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.025557#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.127270#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.239332#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.333498#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.511194#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.606938#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.698215#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.881176#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-00.995908#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.087948#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.212889#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.316168#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.403994#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.499591#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.564515#2831]  INFO -- : Got response: type 0
I, [% d_06  11-11-01.640897#2831]  INFO -- : Got response: type 0
```  

Do you perhaps have any idea what causes this?

**Comment by d-theus** [comment]
Hello, @somejavadev. I'll take a look.
Could you, please, tell me which VNC server do you use? Platform vncrec running on? And maybe server logs also (these tend to be helpful in case of x11vnc).

**Comment by d-theus** [comment]
@somejavadev the problem appears to be on the server side. x11vnc, for instance, it denies any incoming connections when it already has one client connected. It has to do with input events I guess. This behavior is configurable, though.
So I tried to connect with vncrec as a second client to the server with default sharing settings and got the same issue. But it worked fine with adjusted sharing, i.e.  `x11vnc -shared`.
Feel free to reopen this issue if this is not the case.
